name: AwesomeTools
version: 1.0
author: Will
main: me.williamsaada.MorePicks.AwesomeTools
api-version: 1.13

commands:
  at:
    usage: / <command> [give, reload]
    description: Commands for MorePicks plugin

permissions:
  awesometools.give:
    description: The ability to give any player a custom MorePicks tool.
    default: op
    children:
      awesometools.use:
        description: The ability to use a custom MorePicks tool.
        default: true
